### PR TITLE
CBP-4: Infrastructure project reference

### PR DESCRIPTION
**Pull request by witterlee**

### CODE REVIEW

**Comment by lshoo** [comment]
Well Done!

LGTM

**Comment by neeboo** [comment]
Should it state more clearly that how do CBD apply when referenced proposals/projects change or diverse from their origin targets, for example, archived or deleted. How CBP keeps transparency to community and communicates with public? Aside from committee, would it be some working group that can take the job of communication?

**Comment by witterlee** [comment]
Good suggestion, I will seriously consider it and improve this proposal.

> Should it state more clearly that how do CBD apply when referenced proposals/projects change or diverse from their origin targets, for example, archived or deleted. How CBP keeps transparency to community and communicates with public? Aside from committee, would it be some working group that can take the job of communication?

**Comment by neeboo** [comment]
> Good suggestion, I will seriously consider it and improve this proposal.
> 
> > Should it state more clearly that how do CBD apply when referenced proposals/projects change or diverse from their origin targets, for example, archived or deleted. How CBP keeps transparency to community and communicates with public? Aside from committee, would it be some working group that can take the job of communication?

According to 

> **Disclaimers**
CBD does not guarantee any project, including and not limited to financing guarantees, reliability guarantees.

Would be better if adding `Disclaimer.md` or some kind of protocol to the CBP root folder

**Review by neeboo — APPROVED** [review]
LGTM, suggest adding DSCLAIMER.md or Similar open source protocol to project root

**Comment by witterlee** [comment]
Great suggestion! I'll adjust it.
> LGTM, suggest adding DSCLAIMER.md or Similar open source protocol to project root

**Review by neeboo — APPROVED** [review]

**Pull request merged**
