### PR TITLE
CBP-1: CBP draft process

### PR DESCRIPTION
**Pull request by witterlee**

### CODE REVIEW

**Comment by neeboo** [comment]
Do we need CBP author to verify their commit?

**Comment by witterlee** [comment]
> Do we need CBP author to verify their commit?
Do you mean CBP Editor? 
If yes, please pay attention to the [CBP Editor Responsibilities] section，the important role of the editor is to control the quality of the CBP submitted content, so that the submitter can show the CBP to the community more clearly.

**Comment by neeboo** [comment]
> > Do we need CBP author to verify their commit?
> 
> Do you mean CBP Editor? If yes, please pay attention to the [CBP Editor Responsibilities] section，the important role of the editor is to control the quality of the CBP submitted content, so that the submitter can show the CBP to the community more clearly.

I mean the github commit -S to verify the commit is valid and signed

**Comment by witterlee** [comment]
> > > Do we need CBP author to verify their commit?
> > 
> > 
> > Do you mean CBP Editor? If yes, please pay attention to the [CBP Editor Responsibilities] section，the important role of the editor is to control the quality of the CBP submitted content, so that the submitter can show the CBP to the community more clearly.
> 
> I mean the github commit -S to verify the commit is valid and signed

Sounds necessary

**Comment by lshoo** [comment]
I see that there are three kinds of CBP in the proposal, but I only understand that there are two types. Does the second type include two Types?

**Comment by lshoo** [comment]
<quote>Idea - An idea that is pre-draft. This is not tracked within the EIP Repository</quote>
Should the EIP repository be a CBD repository?

**Comment by neeboo** [comment]
> > Idea - An idea that is pre-draft. This is not tracked within the EIP Repository Should the EIP repository be a CBD repository?
> 
> Draft is the stage of submitting PR, and Idea stage does not need to submit PR

LGTM

**Comment by witterlee** [comment]
Ok, this PR will be merged, if there is something that can be optimized, this proposal can be modified by PR

**Pull request merged**
